# Generated by Django 4.2.5 on 2023-09-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
