# Generated by Django 4.2.5 on 2023-09-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeroom', '0002_alter_members_dob_alter_members_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
