# Generated by Django 4.2.5 on 2023-09-27 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeroom', '0003_rename_members_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeroom.member')),
            ],
        ),
        migrations.CreateModel(
            name='AccountSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.FloatField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('total_deposits', models.FloatField()),
                ('total_withdrawals', models.FloatField()),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storeroom.member')),
            ],
        ),
    ]
